title: Paula Alfaro B. # your name (or website title) here
logo: "/images/Foto_Paula.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. Candidate in Applied Mathematics at University of Campinas, Brazil.<br><br>
  I'm interested in neural network models, machine learning, biomathematics and numerical methods. <br><br>
  <a href="https://www.researchgate.net/profile/Rodolfo_Anibal_Lobo">View My ResearchGate Profile</a><br>
  <a href="https://scholar.google.com/citations?user=zN3oqyEAAAAJ&hl=es">View My Google Scholar Profile</a><br>
  <a href="https://github.com/fitolobo"> My GitHub</a><br>
  Contacto: rodolfolobo@ug.uchile.cl
theme: jekyll-theme-minimal

