title: Rodolfo Lobo C # your name (or website title) here
logo: "/images/90086451_1845884882213043_5303571487075074048_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. Candidate at University of Campinas, Brazil. 
  <br><br>
  Areas of Interest: Hipercomplex Neural Networks, Biomathematics and Numerical Methods.
  <br><br>
  <a href="https://www.linkedin.com/in/rodolfo-lobo-carrasco-b4a79a19/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.researchgate.net/profile/Rodolfo_Anibal_Lobo">View My ResearchGate Profile</a> 
theme: jekyll-theme-minimal

