title: Paula Alfaro B. # your name (or website title) here
logo: "/images/Foto_Paula_2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's degree in Music at University of Campinas, Brazil.<br><br>
  I'm interested in music creativity, information and communication technology, piano teaching.<br>
  Currently working on two projects focused on children's musical education and distance music learning for students with visual disabilities.<br><br>
  <a href="mailto:pabarrales@ug.uchile.cl">Contact: pabarrales@ug.uchile.cl</a><br><br>
  <a href="https://www.researchgate.net/profile/Paula_Alfaro4" target="_blank">View My ResearchGate Profile</a><br>  
theme: jekyll-theme-minimal
